function(configure_test_inputs YEAR)
  cmake_path(SET ROOT "${CMAKE_SOURCE_DIR}/tests/aoc${YEAR}/inputs")
  foreach(i RANGE 1 25)
    file(GLOB INPUTS ${ROOT}/day${i}/*.txt)
    foreach(INPUT IN LISTS INPUTS)
      get_filename_component(FILENAME ${INPUT} NAME_WE)
      string(TOUPPER ${FILENAME} FILENAME_UPPER)
      cmake_path(SET INPUTS_DAY${i}_${FILENAME_UPPER} ${INPUT})
      message("Here " ${FILENAME_UPPER})
    endforeach()
  endforeach()
  configure_file(aoc${YEAR}/inputs.hpp.in aoc${YEAR}/inputs.hpp)
endfunction()

